// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB00NZcnsqWpV0UvUID1k2e5K7tHfBkuMs',
    appId: '1:123615218015:web:28d72b49631fae2c80ceea',
    messagingSenderId: '123615218015',
    projectId: 'myfitwizz-1ef5d',
    authDomain: 'myfitwizz-1ef5d.firebaseapp.com',
    storageBucket: 'myfitwizz-1ef5d.appspot.com',
    measurementId: 'G-EVEVK02BDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEh-wgCbcCfzyoYzjeiiyrA3mvZU-Vino',
    appId: '1:123615218015:android:5fddc6d0c8edc59080ceea',
    messagingSenderId: '123615218015',
    projectId: 'myfitwizz-1ef5d',
    storageBucket: 'myfitwizz-1ef5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmRS791lu6ELVmxwq9XRNLBJbNjbuWbA4',
    appId: '1:123615218015:ios:00080e8bf24d236280ceea',
    messagingSenderId: '123615218015',
    projectId: 'myfitwizz-1ef5d',
    storageBucket: 'myfitwizz-1ef5d.appspot.com',
    iosBundleId: 'com.example.myfitwizz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmRS791lu6ELVmxwq9XRNLBJbNjbuWbA4',
    appId: '1:123615218015:ios:af2997c97691020080ceea',
    messagingSenderId: '123615218015',
    projectId: 'myfitwizz-1ef5d',
    storageBucket: 'myfitwizz-1ef5d.appspot.com',
    iosBundleId: 'com.example.myfitwizz.RunnerTests',
  );
}
